### ISSUE TITLE
VAST Macros STOREURL and STOREID unobtainable on iOS/tvOS

### ISSUE THREAD

**Issue by nchavez324** [InteractiveAdvertisingBureau/vast#32]
On iOS/tvOS, there is no API for retrieving the app's App Store ID (e.g. 886445756). So this information would have to be provided by the app developer at their word, which is problematic for brand safety purposes. Likewise for the App Store URL.
  
This is in contrast to the bundle ID (e.g. com.example.app) which is retrievable directly (by say an ads SDK), and also uniquely identifies the app, which is robust for brand safety purposes.

I'd like to know more about the intention/use case for adding these macros, and if we can solve the issue by using the existing APPBUNDLE macro. For instance, Apple's App Store search API allows you to match bundle IDs to App Store IDs. This makes sense to do server-side, offline, but is prohibitive to gate ad display on, client-side.

**Comment by amitshetty** [comment]
Hi Nick,
This has been discussed in the wg quite a bit in the past. The group decided that the best path was to use the storeid since it guaranteed to be unique. 
We released a paper on the topic too - https://iabtechlab.com/blog/guidelines-ctv-ott-device-and-app-identification/
I'd recommend posting this q on the slack group to have a further discussion.
Best,
Amit
